### ISSUE TITLE
don't segfault if a gate's script doesn't exist.

### ISSUE THREAD

**Issue by jonhiggs** [jonhiggs/flamingzombies#9]
```
time="2024-05-01T13:40:44+10:00" level=info msg="executing task" file=lib/fz/task.go task_hash=2103319012 task_name=flappy
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x52c115]

goroutine 6 [running]:
github.com/jonhiggs/flamingzombies/lib/fz.Gate.IsOpen({{0xc000014520, 0xc}, {0xc00001c1a0, 0x1a}, {0x0, 0x0, 0x0}}, 0xc0000c6000)
        /home/jon/src/flamingzombies/lib/fz/gate.go:67 +0xa95
github.com/jonhiggs/flamingzombies/lib/fz.ProcessNotifications.func1()
        /home/jon/src/flamingzombies/lib/fz/notification.go:26 +0x10c7
created by github.com/jonhiggs/flamingzombies/lib/fz.ProcessNotifications in goroutine 1
        /home/jon/src/flamingzombies/lib/fz/notification.go:20 +0x1a
exit status 2
```

**Comment by jonhiggs** [comment]
fixed by #13
